### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bkfox** [bkfox/pepr#8]
# `assets/core`: 
- [x] integrates actions into BaseAccessible's children models
- [ ] adapt existing components to actions: [ ] Content (assets), [x] Subscription (Django)
- [x] fetch pool to fetch once for multiple requests
- [ ] modals for object edition/creation + adapt to existing
  - [ ] backend & flow embedable
  - [x] subscription form modal
  - [ ] content form modal
- [ ] i18n: implement (cf. `vue-i18n`)
- [ ] models: fetch & getOrFetch many
  - [ ] fetch user subscription on context/container load / optional fetch fields with relations on Model fetch

Bugs:
- [ ] Context form: `allow_subscription_request` does not update related input/data value

# `pepr/core`:
- [ ] wrong permissions serialized for role's context?
- [ ] optimise context's join subscription requests

Bugs:
- [ ] Container serializer: `headline` is serialized as `None`
